# Generated by Django 2.2.7 on 2021-04-22 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210422_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
